Repository TEAM-WEBEYE/SERVER, pull requests merged in 2025-05, with the labels that each got.

#30 feat: 리뷰 요약 및 분석
  src/main/java/com/webeye/backend/BackendApplication.java
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/review/application/ReviewService.java
  src/main/java/com/webeye/backend/review/domain/Review.java
  src/main/java/com/webeye/backend/review/dto/request/ReviewSummaryRequest.java
  src/main/java/com/webeye/backend/review/dto/response/ReviewSummaryResponse.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/ClovaXClient.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/ClovaXClientService.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/dto/request/ClovaXContent.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/dto/request/ClovaXMessage.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/dto/request/ClovaXRequest.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/dto/response/ClovaXResponse.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/model/ContentType.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/model/Role.java
  src/main/java/com/webeye/backend/review/infrastructure/mapper/ReviewMapper.java
  src/main/java/com/webeye/backend/review/infrastructure/persistence/ReviewRepository.java
  src/main/java/com/webeye/backend/review/presentation/ReviewController.java
  src/main/java/com/webeye/backend/review/presentation/swagger/ReviewSwagger.java
Labels: ✨feature

#34 feat: 영양성분 비율 분석
  src/main/java/com/webeye/backend/nutrition/application/NutrientRecommendationService.java
  src/main/java/com/webeye/backend/nutrition/domain/NutrientRecommendation.java
  src/main/java/com/webeye/backend/nutrition/domain/type/Gender.java
  src/main/java/com/webeye/backend/nutrition/domain/type/NutrientType.java
  src/main/java/com/webeye/backend/nutrition/dto/request/NutrientRecommendationRequest.java
  src/main/java/com/webeye/backend/nutrition/dto/response/NutrientRecommendationResponse.java
  src/main/java/com/webeye/backend/nutrition/persistent/NutrientRecommendationRepository.java
  src/main/java/com/webeye/backend/nutrition/persistent/init/NutrientInit.java
  src/main/java/com/webeye/backend/nutrition/persistent/init/NutrientRecommendationInit.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/domain/Product.java
  src/main/java/com/webeye/backend/product/domain/ProductAllergy.java
  src/main/java/com/webeye/backend/product/domain/ProductNutrient.java
  src/main/java/com/webeye/backend/product/dto/request/ProductAnalysisRequest.java
  src/main/java/com/webeye/backend/product/dto/response/ProductResponse.java
  src/main/java/com/webeye/backend/product/presentation/swagger/ProductSwagger.java
Labels: ✨feature

#35 feat: 건강 기능 식품 DB 구축
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/healthfood/application/HealthFoodService.java
  src/main/java/com/webeye/backend/healthfood/domain/HealthFood.java
  src/main/java/com/webeye/backend/healthfood/domain/HealthFoodKeyword.java
  src/main/java/com/webeye/backend/healthfood/domain/Keyword.java
  src/main/java/com/webeye/backend/healthfood/domain/type/HealthFoodType.java
  src/main/java/com/webeye/backend/healthfood/dto/HealthFoodResponse.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/client/HealthFoodClient.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/mapper/HealthFoodMapper.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/persistence/HealthFoodKeywordRepository.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/persistence/HealthFoodRepository.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/persistence/KeywordRepository.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/persistence/init/HealthFoodInit.java
  src/main/java/com/webeye/backend/healthfood/presentation/HealthFoodController.java
  src/main/java/com/webeye/backend/healthfood/presentation/swagger/HealthFoodSwagger.java
  src/main/java/com/webeye/backend/rawmaterial/application/service/RawMaterialServiceImpl.java
  src/main/java/com/webeye/backend/rawmaterial/infrastructure/client/RawMaterialClient.java
Labels: ✨feature

#38 refactor: 제품 설명 관련 기능 프롬프트 및 DTO 수정
  src/main/java/com/webeye/backend/allergy/application/AllergyService.java
  src/main/java/com/webeye/backend/allergy/presentation/AllergyController.java
  src/main/java/com/webeye/backend/allergy/presentation/swagger/AllergySwagger.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticService.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticServiceImpl.java
  src/main/java/com/webeye/backend/cosmetic/presentation/CosmeticController.java
  src/main/java/com/webeye/backend/cosmetic/presentation/swagger/CosmeticSwagger.java
  src/main/java/com/webeye/backend/explanation/application/ExplanationService.java
  src/main/java/com/webeye/backend/explanation/dto/request/ProductAnalysisRequest.java
  src/main/java/com/webeye/backend/explanation/dto/request/ProductDetailAnalysisRequest.java
  src/main/java/com/webeye/backend/explanation/presentation/ExplanationController.java
  src/main/java/com/webeye/backend/explanation/presentation/swagger/ExplanationSwagger.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/nutrition/application/NutritionService.java
  src/main/java/com/webeye/backend/nutrition/presentation/NutritionController.java
  src/main/java/com/webeye/backend/nutrition/presentation/swagger/NutritionSwagger.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/dto/request/FoodProductAnalysisRequest.java
  src/main/java/com/webeye/backend/product/dto/response/ProductResponse.java
  src/main/java/com/webeye/backend/product/presentation/ProductController.java
  src/main/java/com/webeye/backend/product/presentation/swagger/ProductSwagger.java
Labels: ♻️refactor

#41 refactor: webConfig 수정
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: 🌏deploy, ♻️refactor

#39 feat: 건강 기능 식품 이미지 분석
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/healthfood/application/HealthFoodService.java
  src/main/java/com/webeye/backend/healthfood/domain/HealthFood.java
  src/main/java/com/webeye/backend/healthfood/dto/HealthFoodAiResponse.java
  src/main/java/com/webeye/backend/healthfood/dto/HealthFoodKeywordResponse.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/mapper/HealthFoodMapper.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/mapper/ProductHealthFoodMapper.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/persistence/HealthFoodRepository.java
  src/main/java/com/webeye/backend/healthfood/presentation/HealthFoodController.java
  src/main/java/com/webeye/backend/healthfood/presentation/swagger/HealthFoodSwagger.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/product/domain/Product.java
  src/main/java/com/webeye/backend/product/domain/ProductHealthfood.java
  src/main/java/com/webeye/backend/product/persistent/ProductHealthFoodRepository.java
Labels: ✨feature

#45 refactor: 화장품 주의 성분 수정
  src/main/java/com/webeye/backend/cosmetic/dto/response/CosmeticResponse.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
Labels: ♻️refactor

#46 feat: 지정된 상품 개요에 따라 상품 요약
  src/main/java/com/webeye/backend/allergy/presentation/AllergyController.java
  src/main/java/com/webeye/backend/allergy/presentation/swagger/AllergySwagger.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticService.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticServiceImpl.java
  src/main/java/com/webeye/backend/cosmetic/presentation/CosmeticController.java
  src/main/java/com/webeye/backend/cosmetic/presentation/swagger/CosmeticSwagger.java
  src/main/java/com/webeye/backend/explanation/application/ExplanationService.java
  src/main/java/com/webeye/backend/explanation/dto/response/PointExplanationResponse.java
  src/main/java/com/webeye/backend/explanation/presentation/ExplanationController.java
  src/main/java/com/webeye/backend/explanation/presentation/swagger/ExplanationSwagger.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/domain/type/OutlineType.java
  src/main/java/com/webeye/backend/product/dto/request/ProductAnalysisRequest.java
  src/main/java/com/webeye/backend/product/dto/request/ProductDetailAnalysisRequest.java
  src/main/java/com/webeye/backend/product/dto/response/DetailExplanationResponse.java
  src/main/java/com/webeye/backend/product/presentation/ProductController.java
  src/main/java/com/webeye/backend/product/presentation/swagger/ProductSwagger.java
Labels: ✨feature, ♻️refactor

#48 feat: OpenAI를 활용한 이미지 분석
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/imageanalysis/application/ImageAnalysisService.java
  src/main/java/com/webeye/backend/imageanalysis/dto/request/ImageAnalysisRequest.java
  src/main/java/com/webeye/backend/imageanalysis/dto/response/ImageAnalysisResponse.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/imageanalysis/presentation/ImageAnalysisController.java
  src/main/java/com/webeye/backend/imageanalysis/presentation/swagger/ImageAnalysisSwagger.java
  src/main/java/com/webeye/backend/product/presentation/swagger/ProductSwagger.java
Labels: ✨feature

#51 feat: 상품 상세 보기 HTML에서 이미지 URL 추출
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/dto/request/ProductDetailAnalysisRequest.java
  src/main/java/com/webeye/backend/product/presentation/swagger/ProductSwagger.java
Labels: ✨feature

#52 refactor: 상품 상세 정보의 이미지를 URL로 받는 API를 HTML로 받도록 수정
  src/main/java/com/webeye/backend/allergy/application/AllergyService.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticServiceImpl.java
  src/main/java/com/webeye/backend/global/error/ErrorCode.java
  src/main/java/com/webeye/backend/healthfood/application/HealthFoodService.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageUrlExtractor.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/imageanalysis/presentation/swagger/ImageAnalysisSwagger.java
  src/main/java/com/webeye/backend/nutrition/application/NutritionService.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/dto/request/FoodProductAnalysisRequest.java
  src/main/java/com/webeye/backend/product/dto/request/ProductAnalysisRequest.java
  src/main/java/com/webeye/backend/product/dto/request/ProductDetailAnalysisRequest.java
Labels: ✨feature

#54 remove: Product Nutrient Unique 조건 제거
  src/main/java/com/webeye/backend/product/domain/ProductNutrient.java
Labels: ✨feature

#55 feat: 쿠팡 내 리뷰 표를 활용한 리뷰 요약 분석
  src/main/java/com/webeye/backend/product/domain/Product.java
  src/main/java/com/webeye/backend/product/persistent/ProductRepository.java
  src/main/java/com/webeye/backend/review/application/ReviewService.java
  src/main/java/com/webeye/backend/review/domain/Review.java
  src/main/java/com/webeye/backend/review/dto/request/ReviewSummaryRequest.java
  src/main/java/com/webeye/backend/review/dto/response/ReviewSummaryResponse.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/ClovaXClientService.java
  src/main/java/com/webeye/backend/review/infrastructure/mapper/ReviewMapper.java
Labels: ✨feature

#62 fix: 이미지 url 추출 오류
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageUrlExtractor.java
Labels: 🐛bug

#64 #63 fix: product nutrient duplicate remove
  src/main/java/com/webeye/backend/product/domain/ProductNutrient.java
Labels: 🐛bug

#69 fix: review avergeRating map -> list으로 수정
  src/main/java/com/webeye/backend/review/application/ReviewService.java
  src/main/java/com/webeye/backend/review/dto/request/ReviewSummaryRequest.java
Labels: 🐛bug

#70 refactor: webConfig 수정
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: ♻️refactor

#81 refactor: webCofig 수정
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: ♻️refactor

#78 feat: 식품 영양성분 도출 기준 함량 추가
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/nutrition/application/NutritionService.java
  src/main/java/com/webeye/backend/nutrition/dto/response/NutrientResponse.java
  src/main/java/com/webeye/backend/nutrition/dto/response/NutritionAiResponse.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/domain/Product.java
  src/main/java/com/webeye/backend/product/dto/response/ProductResponse.java
  src/main/java/com/webeye/backend/rawmaterial/application/RawMaterialService.java
Labels: ✨feature

#83 feat: Product 컬럼 추가 및 Cosmetic 도메인 설계
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticService.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticServiceImpl.java
  src/main/java/com/webeye/backend/cosmetic/domain/CosmeticIngredient.java
  src/main/java/com/webeye/backend/cosmetic/domain/Ingredient.java
  src/main/java/com/webeye/backend/cosmetic/domain/type/IngredientType.java
  src/main/java/com/webeye/backend/cosmetic/infrastructure/mapper/CosmeticIngredientMapper.java
  src/main/java/com/webeye/backend/cosmetic/infrastructure/persistence/CosmeticIngredientRepository.java
  src/main/java/com/webeye/backend/cosmetic/infrastructure/persistence/IngredientRepository.java
  src/main/java/com/webeye/backend/cosmetic/infrastructure/persistence/init/IngredientInit.java
  src/main/java/com/webeye/backend/global/error/ErrorCode.java
  src/main/java/com/webeye/backend/healthfood/application/HealthFoodService.java
  src/main/java/com/webeye/backend/healthfood/domain/HealthFood.java
  src/main/java/com/webeye/backend/healthfood/domain/HealthFoodKeyword.java
  src/main/java/com/webeye/backend/healthfood/domain/Keyword.java
  src/main/java/com/webeye/backend/healthfood/infrastructure/mapper/HealthFoodMapper.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/product/domain/Product.java
  src/main/java/com/webeye/backend/product/domain/type/ProductType.java
  src/main/java/com/webeye/backend/product/persistent/ProductRepository.java
  src/main/java/com/webeye/backend/review/domain/Review.java
Labels: ✨feature

#89 fix: product health food duplicate remove
  src/main/java/com/webeye/backend/product/domain/ProductHealthfood.java
Labels: 🐛bug

#93 fix: product health food duplicate remove
  src/main/java/com/webeye/backend/healthfood/application/HealthFoodService.java
  src/main/java/com/webeye/backend/healthfood/domain/HealthFood.java
  src/main/java/com/webeye/backend/product/domain/ProductHealthfood.java
Labels: 🐛bug

#100 feat: 리뷰 request 수정
  src/main/java/com/webeye/backend/review/application/ReviewService.java
  src/main/java/com/webeye/backend/review/dto/request/ReviewSummaryRequest.java
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/ClovaXClientService.java
  src/main/java/com/webeye/backend/review/presentation/ReviewController.java
Labels: ✨feature

#101 refactor: 상품 상세정보 요약 OpenAI 답변 형식 변경
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/productdetail/application/ProductDetailService.java
  src/main/java/com/webeye/backend/productdetail/domain/type/OutlineType.java
  src/main/java/com/webeye/backend/productdetail/dto/response/AllDetailExplanationResponse.java
  src/main/java/com/webeye/backend/productdetail/presentation/swagger/ProductDetailSwagger.java
Labels: ♻️refactor

#103 refactor: allowed origins 추가
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: ♻️refactor

#105 refactor: 리뷰 로그 추가
  src/main/java/com/webeye/backend/review/infrastructure/clovaX/ClovaXClientService.java
Labels: ♻️refactor

#108 refactor: 음식 상세 분석 각 문장 앞 글머리기호 제거
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
Labels: ♻️refactor

#111 fix: OpenAI 이미지 요청 개수 20개로 제한
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageUrlExtractor.java
  src/main/java/com/webeye/backend/product/application/ProductService.java
  src/main/java/com/webeye/backend/productdetail/application/ProductDetailService.java
Labels: 🐛bug

#115 fix: OpenAI 반환 형식 강제
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageUrlExtractor.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
Labels: 🐛bug

#117 fix: 이미지 한도 개수 조정
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageUrlExtractor.java
Labels: 🐛bug

#118 refactor: image 개수 조정
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageUrlExtractor.java
Labels: ♻️refactor

#120 refactor: cors 추가
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: 🌏deploy, ♻️refactor

#122 refactor: cors 추가
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: ♻️refactor

#126 fix: cors 오류
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: 🚨hotfix

#129 refactor: 식품 제목 선택적 요청
  src/main/java/com/webeye/backend/product/dto/request/FoodProductAnalysisRequest.java
Labels: ♻️refactor

#130 refactor: cors 추가
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: 🌏deploy, ♻️refactor

#135 fix: 이미지 분석 영어로 응답되는 오류 해결
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/product/dto/request/FoodProductAnalysisRequest.java
Labels: 🐛bug

#138 refactor: cors 추가
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: 🌏deploy, ♻️refactor

#140 refactor: cors 추가
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: 🌏deploy, ♻️refactor
