Repository TEAM-WEBEYE/SERVER, pull requests merged in 2025-04, with the labels that each got.

#4 docs: 템플릿 수정
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/refactor_template.md
  .github/pull_request_template.md
Labels: 📝docs, ⚙️setting

#6 feat: CI/CD 자동 배포
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application.yml
Labels: 🌏deploy, ⚙️setting

#9 refactor: Java 버전 변경
  build.gradle
  src/main/java/com/webeye/backend/global/config/OpenAiConfig.java
  src/main/java/com/webeye/backend/global/config/SwaggerConfig.java
Labels: ✨feature

#11 refactor: dockerfile 수정
  Dockerfile
Labels: 🌏deploy, ♻️refactor

#13 refactor: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 🌏deploy, ♻️refactor

#16 feat: webConfig 설정
  src/main/java/com/webeye/backend/global/config/WebConfig.java
Labels: ✨feature, 🌏deploy

#19 feat: OpenAI 를 활용한 이미지 분석 관련 기능 구현
  .coderabbit.yaml
  src/main/java/com/webeye/backend/allergy/application/AllergyService.java
  src/main/java/com/webeye/backend/allergy/dto/response/AllergyResponse.java
  src/main/java/com/webeye/backend/allergy/presentation/AllergyController.java
  src/main/java/com/webeye/backend/allergy/presentation/swagger/AllergySwagger.java
  src/main/java/com/webeye/backend/explanation/application/ExplanationService.java
  src/main/java/com/webeye/backend/explanation/dto/response/DetailExplanationResponse.java
  src/main/java/com/webeye/backend/explanation/dto/response/PointExplanationResponse.java
  src/main/java/com/webeye/backend/explanation/presentation/ExplanationController.java
  src/main/java/com/webeye/backend/explanation/presentation/swagger/ExplanationSwagger.java
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/global/error/ErrorCode.java
  src/main/java/com/webeye/backend/imageanalysis/dto/request/ImageAnalysisPrompt.java
  src/main/java/com/webeye/backend/imageanalysis/dto/request/ImageAnalysisRequest.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/ImageMimeType.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/nutrition/application/NutritionService.java
  src/main/java/com/webeye/backend/nutrition/dto/response/NutritionResponse.java
  src/main/java/com/webeye/backend/nutrition/presentation/NutritionController.java
  src/main/java/com/webeye/backend/nutrition/presentation/swagger/NutritionSwagger.java
Labels: ✨feature

#21 feat: NCP 서버 배포
  .github/workflows/deploy.yml
Labels: 🌏deploy, ⚙️setting

#24 feat: 원재료 영양 성분 Open API
  build.gradle
  src/main/java/com/webeye/backend/global/config/OpenFeignConfig.java
  src/main/java/com/webeye/backend/global/domain/BaseEntity.java
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/global/error/ErrorCode.java
  src/main/java/com/webeye/backend/rawmaterial/application/service/RawMaterialService.java
  src/main/java/com/webeye/backend/rawmaterial/application/service/RawMaterialServiceImpl.java
  src/main/java/com/webeye/backend/rawmaterial/domain/RawMaterial.java
  src/main/java/com/webeye/backend/rawmaterial/dto/RawMaterialResponse.java
  src/main/java/com/webeye/backend/rawmaterial/infrastructure/client/RawMaterialClient.java
  src/main/java/com/webeye/backend/rawmaterial/infrastructure/mapper/RawMaterialMapper.java
  src/main/java/com/webeye/backend/rawmaterial/infrastructure/persistence/RawMaterialRepository.java
  src/main/java/com/webeye/backend/rawmaterial/presentation/RawMaterialController.java
  src/main/java/com/webeye/backend/rawmaterial/presentation/swagger/RawMaterialSwagger.java
Labels: ✨feature

#25 feat: 화장품 분류의 제품에서 주의성분 포함 여부 추출
  src/main/java/com/webeye/backend/allergy/presentation/AllergyController.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticService.java
  src/main/java/com/webeye/backend/cosmetic/application/CosmeticServiceImpl.java
  src/main/java/com/webeye/backend/cosmetic/dto/response/CosmeticResponse.java
  src/main/java/com/webeye/backend/cosmetic/presentation/CosmeticController.java
  src/main/java/com/webeye/backend/cosmetic/presentation/swagger/CosmeticSwagger.java
  src/main/java/com/webeye/backend/explanation/presentation/ExplanationController.java
  src/main/java/com/webeye/backend/global/dto/response/type/SuccessCode.java
  src/main/java/com/webeye/backend/imageanalysis/infrastructure/OpenAiClient.java
  src/main/java/com/webeye/backend/nutrition/presentation/NutritionController.java
Labels: ✨feature
